version: '3.8'

services:
  dev:
    build: .
    container_name: python-dev
    volumes:
      - .:/workspace
      - /workspace/.venv
      - ./mlruns:/app/mlruns
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mlflow
    environment:
      - REDIS_URL=redis://redis:6379
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    stdin_open: true
    tty: true

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

  mlflow:
    container_name: mlflow-server
    image: ghcr.io/mlflow/mlflow:v2.22.0
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_ARTIFACTS_DESTINATION=/mlflow/mlruns
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow/mlflow.db 
      --default-artifact-root /mlflow/mlruns 
      --host 0.0.0.0 
      --port 5000
    restart: unless-stopped

volumes:
  redis_data:
  mlflow_data: