version: '3.8'

services:
  dev:
    build: .
    container_name: python-dev
    volumes:
      - .:/home/devuser/code
      - /home/devuser/code/.venv
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mlflow
    environment:
      - REDIS_URL=redis://redis:6379
    stdin_open: true
    tty: true

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

  mlflow:
    image: python:3.10-slim
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_SERVER_PORT=5000
    command: >
      sh -c "
      pip install mlflow &&
      mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns"
    working_dir: /mlflow

volumes:
  redis_data:
