data_loading:
  batch_size: 1000
  offset: 0
  raw_data_table_name: "raw data"
  columns:
    unique_key: "employee_id"
    to_drop:
    - "employee_id"
    target: "stress_level"
preprocess_data:
  split_ratio: 0.3 # test size