training:
  paths:
    feature_store: "src/stress_detection/feature_store"
    training_data: "data/training_data.parquet"
    testing_data: "data/testing_data.parquet"
  columns:
    unique_key: "employee_id"
    event_timestamp: "event_timestamp"
  model:
  - "random forest"
  - "svm"
