jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack:latest
        ports:
          - 6379:6379
        # options: >-
        #   --health-cmd "redis-cli ping"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5

    env:
      REDIS_URL: redis://localhost:6379
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_EXPERIMENT_NAME: ${{ secrets.MLFLOW_EXPERIMENT_NAME }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install redis-cli
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      # - name: Test Redis connectivity
      #   run: redis-cli -h localhost ping

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: |
          uv venv .venv
          uv pip install -e ".[dev]" --python .venv/bin/python

      - name: Run feature pipeline
        run: |
          source .venv/bin/activate
          python src/stress_detection/pipelines/feature_pipeline.py
